# Generated by Django 5.1.2 on 2024-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='pdfs/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
